# this is a script for loading all R packages that are used in this pipeline
print(x = "################## Loading required packages ########################")
library(tidyverse)
library(cosinor)
library(data.table)
library(estimatr)
library(GGally)
library(ggfortify)
library(ggpubr)
library(glue)
library(mltools)
library(olsrr)
library(parallel)
library(readxl)
library(reshape2)
library(SKAT)
library(viridis)
library(factoextra)
library(aod)
